### ISSUE TITLE
rename tidy and formatted tab titles

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/OmopViewer#124]
@daniellenewby has opinions :)

**Comment by catalamarti** [comment]
happy to discuss @daniellenewby

**Comment by daniellenewby** [comment]
at the moment there are 3 tabs
1) raw
2) tidy
3) formatted

I would remove raw (this is summarised results table?) and allow people to download this and call it a summarised results file 2) is basically raw/searchable table so call it table? 3) pretty/formatted table? I would make the "formatted" tab the first tab as a user this is what i want to look at first to get a general overview then i would at other tables :)

**Comment by catalamarti** [comment]
Raw tab was deleted, only tidy is remaining, the formatted one is defined at package level
