### ISSUE TITLE
default icon for every tab

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/OmopViewer#126]
at the moment some tabs have an icon and some don't

**Comment by catalamarti** [comment]
icons are defined in:
https://github.com/oxford-pharmacoepi/omopViewer/blob/c70122b5d7f36d604a937b31f5aa94b85ab913cc/data-raw/internalData.R#L7-L15

We could have a default icon for non 'onboarded' tabs, although my idea would be that we add here all the tabs for the packages that we want to support.

Possible icons here: https://fontawesome.com/search?m=free&o=r
