### ISSUE TITLE
Exclude buttons for specific inputs throughout the shiny

### ISSUE THREAD

**Issue by edward-burn** [OHDSI/OmopViewer#177]
Would be nice to have the ability to pre-emptively remove certain filters when making the app. For example, a way that lets me say I don't want any input buttons for cohort definition id across all panels of the shiny

![image](https://github.com/user-attachments/assets/3a0ba291-5d26-461f-bda0-657b620a062b)

**Comment by catalamarti** [comment]
duplicated #51
